name: debug

on: 
  push:
    branches:
      - master

jobs:
  build:
    env:
        projName: V2RayG
        projCfg: Release

    runs-on: windows-2019

    steps:

        - name: Checkout master
          uses: actions/checkout@v2.3.3

        - name: Show versions
          run: |
            python --version
            echo "power shell version:"
            $Host.Version

        - name: Export env test
          run: |
            echo "hello=world" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        - name: Show value of env
          run: |
            echo "1. hello = $hello"
            echo "2. hello = ${hello}"
            echo "3. hello = ${ env.hello }"
            echo "4. hello = ${{ env.hello }}"

        - name: Setup .net framework env
          uses: vrnobody/Setup-DotNetFrameworkEnv@v1.2.6

        - name: Restore packages
          run: nuget restore ${env:projName}.sln

        - name: Build with MSBuild
          run: msbuild ${env:projName}.sln -p:Configuration=${env:projCfg}

        - name: Run unit tests
          run: |
            function Invoke-VSTest {
              & "vstest.console.exe" $args
              if(-not $?){ throw "fail!" }
            }
            Invoke-VSTest "V2RayG.Tests\bin\${{ env.projCfg }}\V2RayG.Tests.dll"
            Invoke-VSTest "Apis.Tests\bin\${{ env.projCfg }}\Apis.Tests.dll"
            Invoke-VSTest "Plugins\ProxySetter.Tests\bin\${{ env.projCfg }}\ProxySetter.Tests.dll"

        - name: All done!
          run: echo "All done!"
