name: release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**'  # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:

    runs-on: windows-latest

    env:
        projName: V2RayG
        projCfg: Release
        releaseNoteUrl: "https://vrnobody.github.io/V2RayG/04-dev/10-release-log/"
        verStr: '0.0.x'
        boxAppend: box
        v2rayCorePkgName: 'v2ray-windows-64.zip'
        scriptPkgName: 'scripts-v1.0.4'
        v2rayCoreVer: 'v5.0.3'
        # https://github.com/v2ray/v2ray-core/releases/download/v4.20.0/v2ray-windows-32.zip
        v2rayCoreUrl: 'https://github.com/v2fly/v2ray-core/releases/download'

    steps:
        - name: Checkout master
          uses: actions/checkout@v2.3.3

        - name: Show versions
          run: |
            python --version
            echo "power shell version:"
            $Host.Version

        - name: Setup .net framework env
          uses: vrnobody/Setup-DotNetFrameworkEnv@v1.2.6

        - name: Restore packages
          run: nuget restore ${env:projName}.sln

        - name: Build solution
          run: msbuild ${env:projName}.sln -p:Configuration=${env:projCfg}

        - name: Run unit tests
          run: |
            function Invoke-VSTest {
              & "vstest.console.exe" $args
              if(-not $?){ throw "fail!" }
            }
            Invoke-VSTest "V2RayG.Tests\bin\${{ env.projCfg }}\V2RayG.Tests.dll"
            Invoke-VSTest "Apis.Tests\bin\${{ env.projCfg }}\Apis.Tests.dll"
            Invoke-VSTest "Plugins\ProxySetter.Tests\bin\${{ env.projCfg }}\ProxySetter.Tests.dll"

        - name: Create assets
          shell: pwsh
          run: |
            $scriptsDir = "${env:projName}/Resources/Files/Scripts"
            Compress-Archive -Path ${scriptsDir}/* ${env:scriptPkgName}'.zip'
            $outdir = "${env:projName}/bin/${env:projCfg}"
            Compress-Archive -Path ${outdir}/* ${env:projName}'.zip'
            Invoke-WebRequest -Uri "${env:v2rayCoreUrl}/${env:v2rayCoreVer}/${env:v2rayCorePkgName}" -OutFile "${env:v2rayCorePkgName}"
            Expand-Archive "${env:v2rayCorePkgName}" -DestinationPath "${outdir}/core"
            Remove-Item -path "${outdir}/core/config.json"
            Compress-Archive -Path ${outdir}/* ${env:projName}'-'${env:boxAppend}'.zip'
            $hash1 = Get-FileHash "${env:projName}.zip" -Algorithm MD5
            $hash2 = Get-FileHash "${env:projName}-${env:boxAppend}.zip" -Algorithm MD5
            $hash3 = Get-FileHash "${env:scriptPkgName}.zip" -Algorithm MD5
            $hv1 = $hash1.Hash
            $hv2 = $hash2.Hash
            $hv3 = $hash3.Hash
            echo "hashVgcZip=${hv1}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "hashVgcBoxZip=${hv2}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            echo "hashScriptPkgZip=${hv3}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

        - name: Create Release
          id: create_release
          uses: actions/create-release@master
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ env.verStr }}
              release_name: 'v${{ env.verStr }}'
              body: |
                [Release logs 发布记录](${{ env.releaseNoteUrl }})
                
                #### 变化：
                 * 变化1
                
                #### MD5:
                ${{ env.projName }}.zip (${{ env.hashVgcZip }})
                ${{ env.projName }}-${{ env.boxAppend }}.zip (${{ env.hashVgcBoxZip }})
                ${{ env.scriptPkgName }}.zip (${{ env.hashScriptPkgZip }})

                其中${{ env.projName }}-${{ env.boxAppend }}.zip打包了v2ray-core-win64 ${{ env.v2rayCoreVer }}
                ${{ env.scriptPkgName }}.zip解压后拖进Luna脚本管理器的空白区中即可使用

                #### 注意：
                如果你手动下载v2ray-core，请删掉config.json
              draft: true
              prerelease: false

        - name: Upload ${{ env.scriptPkgName }}.zip
          uses: actions/upload-release-asset@v1.0.1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} 
              asset_path: ./${{ env.scriptPkgName }}.zip
              asset_name: ${{ env.scriptPkgName }}.zip
              asset_content_type: application/zip

        - name: Upload ${{ env.projName }}.zip
          uses: actions/upload-release-asset@v1.0.1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} 
              asset_path: ./${{ env.projName }}.zip
              asset_name: ${{ env.projName }}.zip
              asset_content_type: application/zip

        - name: Upload ${{ env.projName }}-${{ env.boxAppend }}.zip
          uses: actions/upload-release-asset@v1.0.1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} 
              asset_path: ./${{ env.projName }}-${{ env.boxAppend }}.zip
              asset_name: ${{ env.projName }}-${{ env.boxAppend }}.zip
              asset_content_type: application/zip
